# Generated by Django 4.2.4 on 2023-08-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_message_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="image",
            field=models.ImageField(
                default="default.jpg", null=True, upload_to="img/%y"
            ),
        ),
    ]
